### ISSUE TITLE
Broken User Signup.

### ISSUE THREAD

**Issue by lilpolymath** [lilpolymath/detox#1]
## The Normal flow of the app.

1. New user signs in with Email, Preferred username and password.
2. User details(uid, email and username) get sent to the Realtime database and added to the list of users
3. Logged in user receives a new list of registered users.

## Problems
The current issue is that Process 2 is skipped therefore causing;
1. User's details is not sent to the database.
2. Other users are not notified of the new users.

## Files to check to fix.
Signup.js

**Comment by imoris11** [comment]
Hey, here's a few things you can try. 

1. Make sure your auth is actually returning the user. In my experience, this method doesn't work 100% of the time as you expect. 

```
const user =  firebase.auth().currentUser
``` 
may not return the user in time for you to call writeData. If that is the case, you can retrieve the user using the `onAuthStateChanged` listener instead.

Assuming that isn't the problem, then 

2. Check your writeData method. A couple of things can be updated here. Try 

```
firebase
      .database()
      .ref().child('users').child(userId)
      .update({
        username: name,
        email: email
      }, (error) => {
  if (!error) {
     this.props.navigation.navigate('Login')
}
})
```

Either or both of this should fix your issue.


GOOD LUCK

**Comment by lilpolymath** [comment]
Tried ht fix. It works and it also turns out that I was using

`firebase.database().ref("users')`
